server:
  port: 8083

spring:
  application:
    name: listing-service

  datasource:
    url: jdbc:mysql://localhost:3306/motohive_listings?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: ListingServiceHikariPool
      maximum-pool-size: 15
      minimum-idle: 3

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

motohive:
  services:
    vehicle-service-url: ${VEHICLE_SERVICE_URL:http://localhost:8082}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method       # sorts by GET/POST/PATCH/DELETE
    tags-sorter: alpha              # sorts controllers alphabetically
    try-it-out-enabled: true        # enables Try it out by default
  show-actuator: false

logging:
  level:
    com.motohive.listingservice: DEBUG