server:
  port: 8083

spring:
  application:
    name: listing-service

  datasource:
    url: jdbc:mysql://localhost:3306/motohive_listings?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: ListingServiceHikariPool
      maximum-pool-size: 15    # listings may have higher load
      minimum-idle: 3

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: listing-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.motohive.*"

# Feign entity config for calling vehicle-service
motohive:
  services:
    vehicle-service-url: ${VEHICLE_SERVICE_URL:http://localhost:8082}
    user-service-url: ${USER_SERVICE_URL:http://localhost:8081}